# This workflow will automatically build and deploy the MkDocs site 
# to GitHub Pages using the gh-pages branch.

name: Deploy MkDocs Documentation

on:
  # Triggers the workflow on push events to the main branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN to allow deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    # --- FIX APPLIED HERE: Changed runs_on to runs-on ---
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Python environment (MkDocs is Python-based)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # 3. Install MkDocs and the Material Theme
      - name: Install dependencies
        run: |
          pip install mkdocs-material

      # 4. Deploy the site using the official deploy action
      - name: Deploy MkDocs to GitHub Pages
        uses: peaceiris/actions-mkdocs@v2.0.0
        with:
          # The configuration file is mkdocs.yml in the root
          configuration: mkdocs.yml
          # The branch to push the static site files to (this is where GitHub Pages serves from)
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The target branch for the built site (defaults to gh-pages)
          publish_branch: gh-pages
          # The directory where MkDocs builds the static files (defaults to site)
          publish_dir: site
