# This workflow uses official GitHub actions to build the MkDocs site
# and deploy it to GitHub Pages.

name: Deploy MkDocs Documentation

on:
  # Triggers the workflow on push events to the main branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN to allow deployment
permissions:
  contents: read # Read permission for checkout
  pages: write   # Write permission to deploy to GitHub Pages
  id-token: write # Required for deployment action

jobs:
  # 1. Build the MkDocs site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for proper git-based versioning if MkDocs uses it
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          # Install MkDocs and the Material theme
          pip install mkdocs-material

      - name: Build MkDocs Site
        run: mkdocs build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 2. Upload the built static files as an artifact
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The MkDocs build command outputs static files to the 'site' directory
          path: './site'
          
  # 3. Deploy the uploaded artifact to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # This job must wait for the 'build' job to finish
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
